const segment = (value: string): string => encodeURIComponent(value);

export const GATEWAY_ENDPOINTS = {
  actuatorCommands: (deviceId: string) => `actuators/${segment(deviceId)}/commands`,
  actuators: 'actuators',
  assistantContext: 'assistant/context',
  assistantMessage: (sessionId: string) => `assistant/sessions/${segment(sessionId)}/messages`,
  assistantSessions: 'assistant/sessions',
  cameraCaptures: (deviceId: string) => `camera/${segment(deviceId)}/captures`,
  cameraImageFile: (imageId: string) => `camera/images/${segment(imageId)}/file`,
  cameraImages: (deviceId: string) => `camera/${segment(deviceId)}/images`,
  device: (deviceId: string) => `devices/${segment(deviceId)}`,
  deviceMeta: (deviceId: string) => `devices/${segment(deviceId)}/meta`,
  deviceRegistration: (deviceId: string) => `devices/${segment(deviceId)}/registration`,
  devices: 'devices',
  historyActuator: 'history/actuator',
  historyCamera: 'history/camera',
  historyEvents: 'history/events',
  historySensor: 'history/sensor',
  historySensorExport: 'history/sensor/export',
  overview: 'overview',
  systemGateway: 'system/gateway',
  systemLogs: 'system/logs',
  systemMqtt: 'system/mqtt',
  systemNetwork: 'system/network',
  systemStatus: 'system/status',
  systemSync: 'system/sync',
  systemSyncRuns: 'system/sync/runs',
  telemetryLatest: 'telemetry/latest',
  telemetrySeries: (deviceId: string) => `telemetry/${segment(deviceId)}/series`,
} as const;
